vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.swapfile = false
vim.opt.cursorline = true
vim.opt.clipboard = "unnamedplus"
-- vim.opt.winb:order = "rounded"
